spring.application.name=backend1
server.port=8081



# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://dpg-d72qp8h4tr6s73djeddg-a.frankfurt-postgres.render.com/veradb?sslmode=require
spring.datasource.username=hiba
spring.datasource.password=IMhVBcJgQV9ZB2reBs0ayAlaH6niGaEN
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=invitini.events@gmail.com
spring.mail.password=ipny yjuh pzar tigs
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


minio.url=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin123
minio.bucket-name=vera-events-images

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.config.import=optional:classpath:application-local.properties